config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'pages#home'

  resources :pages, only: :show
  resources :erstgespraech, only: :index
  resources :impressum, only: :index

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/erstgespraech_controller.rb
class ErstgespraechController < ApplicationController
  def home
  end
end

app/controllers/impressum_controller.rb
class ImpressumController < ApplicationController
  def home
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/erstgespraech_helper.rb
module ErstgespraechHelper
end

app/helpers/impressum_helper.rb
module ImpressumHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/erstgespraech/index.html.erb
<div class="containerr flex flex-wrap h-full">

  <iframe src="https://koalendar.com/e/erstgesprach-koayvDmC?embed=true" width="100%" height="800px" frameborder="0"></iframe>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.css" />
  <%= link_to root_path do %>
      <button  type="button" class="slide">
        Zurück
        <i class="icon-arrow-left"></i>
      </button>
  <% end %>

</div>

app/views/impressum/index.html.erb
<div class="container">

<h2>Impressum</h2>
<h4>Angaben gemäß § 5 TMG:</h4>
<p><br><em>Florian Ernst</em></p>
<h4><b>Postanschrift:</b></h4>
<p><em>Landsberger Straße 37<br>04157 Leipzig<br></em></p>
<h4><b>Kontakt:</b></h4>
<p><em>Telefon: +49 173 83 11 4 33<br>E-Mail: florian@ernst-rethink.de</em></p>
<p><br></p>
<p></p><h4>Hinweise zur Website</h4>
<p></p><h4>Information gemäß § 36 VSBG</h4>
<p>Gemäß § 36 VSBG (Verbraucherstreitbeilegungsgesetz – Gesetz über die alternative Streitbeilegung in Verbrauchersachen) erklärt der Betreiber dieser Website:</p>
<p>Wir sind weder bereit noch verpflichtet, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen.</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="de">
  <head>
    <title>Florian Ernst</title>
    <meta name="viewport" content="width=device-width,initial-scale=.8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container" content="width=device-width">
  <div class="header">
    <div class="logo">
      <p id="logo-florian"><b> ernst - <br> <u>re:</u>think </b><br>
      <div id="logo-ernst">FLORIAN ERNST</div></p>
    </div>

    <nav class="navi">
      <ul>
        <li class="border-none"><%= link_to "Angebot", "#angebot" %> </li>
        <li class="border-none"><%= link_to "Über mich", "#übermich" %> </li>
        <li class="border-around border-none2"><%= link_to "Erstgespräch", erstgespraech_index_path %> </li>
      </ul>
    </nav>
  </div>

  <div class="header header-pad">
    <div class="beste">
      <div class="sidebar logo-gross">
        <div class="text">
          <h1> <b> ernst - <br><u>re:</u>think</h1></b>
          <h3 id="text-up">NEW WORK<br>KULTURWANDEL<br>PERSONALBINDUNG</h3>
        </div>
      </div>

      <h2>Holen Sie <br> das Beste aus <br> Ihren Teams <br></h2>

      <%= link_to erstgespraech_index_path do %>
        <div class="btn">
          <button class="fill">ERSTGESPRÄCH</button>
        </div>
      <% end %>
    </div>
    <div id="angebot"></div>
  </div>

  <div>
    <p class="angebot">Angebot</p>
  </div>

  <div class="header-for-content with-border">
    <div class="item-left">
      <h4><b>New Work -</b><br> der Weg in eine <br>bessere Arbeitswelt</h4>
    </div>

    <div class="content-right">
      <p>New Work ist in aller Munde aber was bedeutet es für das Team? Welche Herausforderungen entehen und wie können diese überwunden werden?</p>
    </div>
  </div>

  <div class="header-for-content with-border">
    <div class="item-left">
      <h4><b>Digitales Arbeiten -</b><br> Teamgefühl trotz <br>Distanz</h4>
    </div>

    <div class="content-right">
      <p>Digitales Arbeiten verändert Strukturen und die Art und Weise, wie wir miteinander arbeiten. Dabei ist es wichtig, dass jede:r Mitarbeiter:in gesehen wird. Beste Zusammenarbeit und Teamgefühl ist keine Frage der Distanz!</p>
    </div>
  </div>

  <div class="header-for-content with-border">
    <div class="item-left">
      <h4><b>Interkulturelles Managment -</b><br> Bedürfnisse (er)kennen und<br>berücksichtigen</h4>
    </div>

    <div class="content-right">
      <p>Vielfalt bringt viele Vorteile in ein Team. Welche Veränderungen müssen bedacht werden? Welche Bedürfnisse müssen berücksichtigt werden und wie kann ein interkulturelles Team erfolgreich organisiert werden?</p>
    </div>
  </div>

  <div class="header-for-content with-border">
    <div class="item-left">
      <h4><b>Kulturwandel -</b><br> Mindset als Antrieb</h4>
    </div>

    <div class="content-right">
      <p>(Unternehmens-) Kultur ist ein dynamischer Prozess der keinen Stillstand kennt. Was braucht es um alte Strukturen aufzubrechen und neue Impulse aufzunehmen, die eine Team- und Unternehmenskultur zu mehr Effizienz, Produktivität und Zufriedenheit führt?</p>
    </div>
  </div>

  <div class="header-for-content with-border">
    <div class="item-left">
      <h4><b>Personalbindung -</b><br> Glück als <br> Wettbewerbsvorteil</h4>
    </div>

    <div class="content-right">
      <p>Ein Impulsworkshop, der Ihnen aufzeigt welche Methoden und Tools angewendet werden können, um Mitarbeiter:innen Zufrieden, Glücklich und Motiviert an ihr Unternehmen bindet</p>
    </div>
  </div>

  <div class="header2" id="übermich">
    <div class="werbetext">
      <p><b> Ich habe ein Workshop-Programm entwickelt das speziell dazu da ist, Teamleads, in den sich schnell entwickelenden Zeiten, auf die modernen Anforderungen der neuen Arbeitswelt vorzubereiten.</b></p>
    </div>
  </div>


  <div class="header3">
    <div class="header-for-content">
      <div class="item-left-pic">
        <h4 id="erstgespräch"><b>Würden Sie gerne mehr erfahren?</b></h4>
        <div class="border-blue">
          <p>Erstgespräch</p>
          <%= link_to erstgespraech_index_path do %>
        <div class="btn">
          <button class="fill">BUCHEN</button>
        </div>
        <% end %>
          <p>30 min</p>
        </div>
        <div>
          <p id="text-margin"><b> Ich bin da, um mit meiner Strategie, Ihre Teams und damit auch Ihr Unternehmen auf die neuen Arbeitswelten vorzubereiten.</b></p>
          <p id="text-margin">Mein Name ist Florian Ernst, ich verknüpfe die Themen New Work, Kulturwandel und Personalbindung zu einem Netz, welche bestehenden Mitarbeiter:innen am Unternehmen bindet und potenzielle Mitarbeiter anzieht. <br> <br> Dabei lege ich meinen Fokus ganz auf die Teamkultur, welche ich durch Workshops und Coachings mit den einzelnen Teammitgliedern, als auch mit den Teamleads Stärke und Festigkeit verleihe.</p>
        </div>
      </div>

      <div class="pic-right">
        <%= image_tag 'profil.jpg', alt: 'Florian Ernst', id: 'profil-jpg' %>
      </div>

    </div>
  </div>


  <div class="footer-flex">

    <div class="footer">

      <div class="item-footer">

        <h4 class="item-footer-bold"><b>Lassen Sie uns <br> zusammen arbeiten</h4><br>
        <p class="item-footer2">
        Florian Ernst <br>
        Landsberger Straße 37 <br>
        04157 Leipzig </p>

        <div>
          <div class="social-icons">
            <%= image_tag "phone.png", :class => "soc"%>
            <span class="teext"><a href="tel:+49 173 83 11 4 33" class="soc">+49 173 83 11 4 33</a></span> <br>
          </div>

          <div class="social-icons">
            <%= image_tag "mail.png", :class => "soc"%><%= mail_to "florian@ernst-rethink.de", 'florian@ernst-rethink.de', :style=>'color: #fffe9a;'%><br>
          </div>

          <div class="social-icons">
            <a target="_blank" href="https://www.linkedin.com/in/ernst-florian/"><%= image_tag "linked.png", :class => "soc"%></a><a href="https://www.linkedin.com/in/ernst-florian/" target="_blank" class="teext">/ernst-florian</a></p>
          </div>
        </div>

        <div class="social-icons">
          <%=link_to "Impressum", impressum_index_path(@impressum), :class => "impressum"%>
        </div>
      </div>

    </div>

    <div class="content-center">
      <%= video_tag "video.mp4", autoplay: :autoplay, loop: :loop, muted: :muted, class: "content-video" %>
    </div>

  </div>





  <a href="#" class="top top1">Start &#8593;</a>


</div>

app/views/partials/_calendar.html.erb
<iframe src="https://koalendar.com/e/meet-with-euven-beucht?embed=true" width="100%" height="800px" frameborder="0"></iframe>